config/routes.rb
RetroPie::Application.routes.draw do

  resources :faqs

  resources :payments

  resources :order_items

  resources :statuses
  
  resources :users do
    collection do
      post 'receipt'
    end
  end

  resources :items

  resources :orders do
    member do
      patch 'update'
      get 'verify'
      post 'charge'
      post 'cash'
    end
    collection do
      post 'update_status'
      get 'appreciation'
      get 'sorry'
      get 'status'
      get 'stats'
    end
  end

  resources :categories

  get 'manage', to: 'static_pages#manage'

  post 'scrape_data', to: 'items#scrape_data'

  get 'contact_me', to: 'static_pages#contact_me'
  post 'contact_me', to: 'static_pages#contact_me'

  root 'static_pages#index'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    before_action :authenticate, only: :manage
    
  def index
    @title = "Play all the games!"
  end

  def manage
    @title = "Overview of Site"
  end

  def contact_me
    if params["commit"] && params["commit"] == 'Send Question'
      ContactMeMailer.contact_me_send_mail(params['name'],params['email'],params['body'],).deliver
      redirect_to root_path, notice: 'Thanks for reaching out to me. I will get back to you ASAP!'
    end
  end

end

app/views/static_pages/_header.html.haml
#header.text-center
	=link_to 'Home', root_path, class: "btn btn-info" + (params["controller"] == 'static_pages' && params["action"] == 'index' ? " active" : "")
	=link_to 'Bake my Pie', new_order_path, class: "btn btn-danger" + (params["controller"] == 'orders' && params["action"] == 'new' ? " active" : "")
	=link_to 'Check Order Status', status_orders_path, class: "btn btn-info" + (params["controller"] == 'orders' && params["action"] == 'status' ? " active" : "")
	=link_to 'Contact Me', contact_me_path, class: "btn btn-info" + (params["controller"] == 'static_pages' && params["action"] == 'contact_me' ? " active" : "")
	=link_to 'FAQ', faqs_path, class: "btn btn-info" + (params["controller"] == 'faqs' ? " active" : "")

app/views/static_pages/contact_me.html.haml
%div.row
  %div.col-md-8.col-md-offset-2.wrapper
    %h2.text-center Contact Me
    %p.text-center
      Have a question, comment or anything else to tell me. Put it here and I will try to get back to you in a timly fassion.
    = form_tag("/contact_me", method: "post", class: "form") do
      .container-fluid
        .row
          .col-md-12
            %div.form-group
              %p
                = label_tag(:name_label, "Name:")
              = text_field_tag(:name, params["name"], class: "form-control")
            %div.form-group
              %p
                = label_tag(:email_label, "Email Address:")
              = email_field_tag(:email, params["contact_info"], class: "form-control")
            %div.form-group
              %p
                = label_tag(:body_label, "Reason for contact:")
              = text_area_tag(:body, params["body"], class: "form-control contact_me_body")
            %div.form-group
              %p
                = recaptcha_tags
            %div.form-group
              .actions
                = submit_tag("Send Question",class: 'btn btn-default')

app/views/static_pages/index.html.haml
.row
  .col-md-12.wrapper
    .row
      .col-md-10.col-md-offset-1
        %p#notice= notice
        %p
          %h3.text-center.margin-10-top
            How long has it been since you played an original Nintendo game?  
          %h4.text-center
            Do you even have your old consoles anymore??  
          %h3.text-center.margin-10-top
            Want to play old games whenever you want?!
.row
  .col-md-12.wrapper
    .row
      .col-md-10.col-md-offset-1
        %p.text-center
          What I am offering is to put together a RetroPie console for you. I will configue it and make sure the contorllers you buy are set up. I did not make this system or even write any code for the retro pie or emulationstation.  
.row
  .col-md-12.wrapper
    .row
      .col-md-10.col-md-offset-1
        %p
          This device is a small computer in a case approximately 4” x 2 ½” x 1 ½” tall. It has an HDMI port that directly connects to your TV and has 4 USB ports to connect to USB controllers.
.row
  .col-md-12.wrapper
    .row
      .col-md-10.col-md-offset-1
        %p
          The Raspberry Pi will show up to your house ready to plug in and play *YAY!* But, if you are having difficulty with the system initially, I am more than willing to help get you up and running. Please use the 
          = link_to 'contact me', contact_me_path
          form for troubleshooting and I will respond to you in a timely fashion.

  .col-md-12.wrapper
    .row
      .col-md-10.col-md-offset-1
        %p
          For legal reasons, I am NOT selling or providing games.
        %strong
          The RetroPie SD-card includes emulators for the following systems:
        %ul
          %li
            Atari 800
          %li
            Atari 2600
          %li
            C64
          %li
            Intellivision
          %li
            Amstrad CPC
          %li
            Game Boy
          %li
            Game Boy Advance
          %li
            Game Boy Color
          %li
            Sega Game Gear
          %li
            Nintendo Entertainment System
          %li
            Sega Master System / Mark III
          %li
            Sega Mega Drive / Genesis
          %li
            Sega Mega-CD / CD
          %li
            Sega 32X
          %li
            Super Nintendo Entertainment System

app/views/static_pages/manage.html.haml
%div.row
  %div.col-md-8.col-md-offset-2
    %p
      =link_to 'Items', items_path
    %p
      =link_to 'Categories', categories_path
    %p
      =link_to 'Status', statuses_path
    %p
      =link_to 'Orders', orders_path