config/routes.rb
RetroPie::Application.routes.draw do

  resources :faqs

  resources :payments

  resources :order_items

  resources :statuses
  
  resources :users do
    collection do
      post 'receipt'
    end
  end

  resources :items

  resources :orders do
    member do
      patch 'update'
      get 'verify'
      post 'charge'
      post 'cash'
    end
    collection do
      post 'update_status'
      get 'appreciation'
      get 'sorry'
      get 'status'
      get 'stats'
    end
  end

  resources :categories

  get 'manage', to: 'static_pages#manage'

  post 'scrape_data', to: 'items#scrape_data'

  get 'contact_me', to: 'static_pages#contact_me'
  post 'contact_me', to: 'static_pages#contact_me'

  root 'static_pages#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
	attr_accessor :items
	after_initialize :set_defaults
	has_many :order_items, dependent: :destroy
	has_many :payments
	belongs_to :user
 	# after_save :update_total
  monetize :total_cents, :cost_cents, :shipping_price_cents

  def refigure_totals
  	cost = 0
  	total = 0
  	OrderItem.where(order_id: self.id).each do |item|
  		cost += ( item.cost_cents * item.quantity)
  		total += ( item.price_cents * item.quantity)
  	end
  	self.update_attributes(cost_cents: cost, total_cents: total)
  end

	def local_shipping
		if self.delivery_type && self.delivery_type.present?
			return true if (self.shipping_info && self.shipping_info.present?) || (self.delivery_type == 'local_pickup')
		end
		return false
	end

	def status
		 return Status.find(self.status_id)
	end

	def set_defaults
		self.status_id = Status.all.where(name: 'Unsubmitted').first.id unless self.status_id || Status.all.length < 1
		self.order_id = SecureRandom.hex(6) unless self.order_id
		self.shipping_price = 0 unless self.shipping_price
	end

	def order_items_builder(user_items)
		final_items = []
		user_items.keys.each do |category|
			user_items[category].keys.each do |item_id|
				if user_items[category][item_id].keys.include?('ordered')
					final_items.push({item_id: item_id, quantity: user_items[category][item_id]["quantity"]})
				end
			end
		end
		create_order_items(final_items)
	end

	# def calculate_cost
	# 	return stats[1]
	# end

	def stats
		item_total = 0
		item_cost = 0
		self.order_items.each do |item|
			item_total += item.price.to_f
			item_cost += item.cost.to_f
		end
		return item_total, item_cost
	end

	# def has_details?
	# 	return true if self.shipping_info.length > 0
	# 	return true if self.special_instructions.length > 0
	# 	return false
	# end

	# def ordered_items(category_items)
	# 	binding.pry
	# 	base_item = []
	# 	ordered_items = []
	# 	category_items.keys.each do |key|
	# 		category_items[key]['item_id'] = key
	# 		base_item << category_items[key] if category_items[key].values.include?('true')
	# 		ordered_items << category_items[key] if category_items[key].keys.include?('ordered')
	# 	end
	# 	if base_item.count > 0
	# 		return base_item - ordered_items
	# 	else
	# 		return ordered_items - base_item
	# 	end
	# end

	def create_order_items(items)
		items.each do |item|
			db_item = Item.where(id: item[:item_id]).first

			if oi = OrderItem.where(order_id: self.id, item_id: item[:item_id]).first
				oi.quantity = item[:quantity]
			else
				oi = OrderItem.new(item_id: item[:item_id], quantity: item[:quantity], price: db_item.figure_price, cost: db_item.cost, order_id: self.id)
			end
			oi.save
		end
	end

	# def verify_price(their_price, my_price)
	# 	return true if their_price == my_price
	# 	return false
	# end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, only: [:index, :destroy]
  skip_before_action :verify_authenticity_token, only: [:update_status, :appreciation]
  # GET /orders
  # GET /orders.json
  def index
    sort_order = params["sort_order"] || 'DESC'
    @sort_order = sort_order == 'ASC' ? 'DESC' : 'ASC'

    # @sort_by = params["sort_by"] || 'name'
    
    @statuses = Status.all.pluck(:name, :id)
    # @orders = Order.order("#{@sort_by} #{@sort_order}")
    @orders = Order.all
    if params["table_only"] && params["table_only"] == "true"
      render partial: 'index_table' and return
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    binding.pry
  end

  # def update_status
  #   UpdatePaymentInfo.perform_async(params)
  #   render :text => ""
  # end

  def status
    @statuses = Status.all
    # if params["order_id"]
    #   order = params["order_id"]
    # elsif session[:my_pie_order]
    #   order = session[:my_pie_order]
    # end
    # if order
    #   @order = Order.where(order_id: order).first
    # end
    # @order = "An order with the id #{order} was not found<br>If an order was not verified I will delete it after a few days." unless @order
    # @title = "Check order status"
  end

  # GET /orders/new
  def new
    if order_id = cookies[:_bmp_order_id]
      if @order = Order.find_by_order_id(order_id)
        @order = nil unless @order.status.name == 'Unsubmitted'
      else
        @order = Order.new
        cookies[:_bmp_order_id] = @order.order_id
      end
    end

    unless @order
      @order = Order.new
      cookies[:_bmp_order_id] = @order.order_id
    end
    # @user = User.new
    # @state_abreviations = ['AK','AL','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY']
    @categories = {}
    Category.all.collect{|cat| [ cat.id, cat.name] }.each do |cat|
      @categories[cat[1]] = Item.all.where(category_id: cat[0]).where(base_item: true) + Item.all.where(category_id: cat[0]).where(base_item: false)
    end
    @delivery_types = [['Local Pickup','local_pickup'],['Delivery','delivery']]
  end

  # GET /orders/1/edit
  def edit
    @order = Order.where(order_id: params["id"]).first
    @user = User.find_by_id(params["user_id"])
    @payment = Payment.find_by_id(params["payment_id"])
    @categories = {}
    Category.all.collect{|cat| [ cat.id, cat.name] }.each do |cat|
      @categories[cat[1]] = Item.all.where(category_id: cat[0]).where(base_item: true) + Item.all.where(category_id: cat[0]).where(base_item: false)
    end
    # @categories["Service Charge"] = [Item.service_charge]
    # @delivery_types = [['Local Pickup','local_pickup'],['Delivery','delivery']]
  end

  def verify
    @order = Order.find_by_order_id(params["id"])
    @user = User.find_by_id(params["user_id"])
    @payment = Payment.where(id: params["payment_id"]).first
    if params["commit"]
      @order.status_id = Status.find_by_name('Ordered')
      if @order.save
        EmailedReceiptMailer.emailed_receipt_send_mail(@user).deliver
        redirect_to appreciation_orders_path, { notice: 'Order status has been updated. You will be contacted shortly.' }
      else
        redirect_to verify_order_path(params["id"], user_id: params["user_id"], payment_id: params["payment_id"]), {notice: 'Some error prevented updating the information.' }
      end
    end
  end

  def cash
    if order = Order.find_by_order_id(params["id"])

      success = false

      payment = Payment.new(order_id: order.id, amount_cents: order.total_cents, status: 'need to pick up', method: 'cash')
      if payment.save
        success = true
      end

      if success
        cookies[:_bmp_order_id] = nil
        status = Status.find_by_name('Payment Processing')
        order.update_attribute(:status_id, status.id || nil)
        redirect_to appreciation_orders_path and return
      else
        flash[:error] = e.message
        redirect_to verify_order_path(id: order.id) and return
      end

    end
  end

  def charge
    if order = Order.find_by_order_id(params["id"])
      status = Status.find_by_name('Payment Processing')
      order.update_attribute(:status_id, status.id || nil)
      begin
        charge = Stripe::Charge.create(
          :amount => order.total_cents, # amount in cents, again
          :currency => "usd",
          :source => params[:stripeToken],
          :description => "Bake My PIe"
        )
      rescue Stripe::CardError => e
        status = Status.find_by_name('Payment Denied')
        order.update_attribute(:status_id, status.id || nil)
        flash[:error] = e.message
        redirect_to verify_order_path(id: order.id) and return
      end

      success = false

      if charge.status == 'succeeded' && charge.source.cvc_check == 'pass' && charge.source.cvc_check == 'pass'
        payment = Payment.new(order_id: order.id, amount_cents: charge.amount, status: charge.status, method: 'card', meta: charge)
        if payment.save
          success = true
        end
      end

      if success
        cookies[:_bmp_order_id] = nil
        status = Status.find_by_name('Payment Recieved')
        order.update_attribute(:status_id, status.id || nil)
        redirect_to appreciation_orders_path and return
      else
        flash[:error] = e.message
        redirect_to verify_order_path(id: order.id) and return
      end

    end
    binding.pry
  end

  def appreciation

    # UpdatePaymentInfo.perform_async(params)
  end

  # def submit_order
  #   binding.pry
  #   @order = Order.where(order_id: params["id"]).first
  #   @user = User.find_by_id(params["OrderId"])
  #   @order = Order.where(order_id: params["order"]["order_id"]).first
  #   @order.status_id = Status.find_by_name('Ordered')
  #   @order.cost = @order.calculate_cost
  #   if @order.save
  #     redirect_to order_path(@order.order_id), { notice: 'Order status has been updated. You will be contacted shortly.' }
  #   else
  #     redirect_to verify_order_path(@order.order_id), {notice: 'Some error prevented updating the information.' }
  #   end
  # end

  # POST /orders
  # POST /orders.json
  def create
    if params["id"].present?
      if @order = Order.find_by_id(params["id"])
        @order.order_items.destroy_all
      end
    end
    @order = Order.new(order_params) unless @order

    respond_to do |format|
      if verify_recaptcha && @order.save
        @order.order_items_builder(params["order"]["items"])
        @order.refigure_totals
        cookies[:_bmp_order_id] = @order.order_id
        format.html { redirect_to new_user_path(order_id: @order.order_id) }
        format.json { render action: 'show', status: :created, location: @order }
      else
        @order.errors.add(:captcha, "Please fill out captcha") unless verify_recaptcha
        @categories = {}
        Category.all.collect{|cat| [ cat.id, cat.name] }.each do |cat|
          @categories[cat[1]] = Item.all.where(category_id: cat[0]).where(base_item: true) + Item.all.where(category_id: cat[0]).where(base_item: false)
        end
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def stats
    # @orders = Order.all
    # return_hash = {}
    # @orders.each do |order|
    #   order["items"] = order.calculate_cost
      
    # end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    if params["id"].present?
      if @order = Order.find_by_id(params["id"])
        @order.order_items.destroy_all
      end
    end
    @order = Order.new(order_params) unless @order

    respond_to do |format|
      if @order.save
        @order.order_items_builder(params["order"]["items"])
        @order.refigure_totals
        cookies[:_bmp_order_id] = @order.order_id
        format.html { redirect_to new_user_path(order_id: @order.order_id) }
        format.json { render action: 'show', status: :created, location: @order }
      else
        @order.errors.add(:captcha, "Please fill out captcha") unless verify_recaptcha
        @categories = {}
        Category.all.collect{|cat| [ cat.id, cat.name] }.each do |cat|
          @categories[cat[1]] = Item.all.where(category_id: cat[0]).where(base_item: true) + Item.all.where(category_id: cat[0]).where(base_item: false)
        end
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_orders
    params["changed_orders"].split(',').each_slice(2) do |id,status_id|
      if order = Order.where(order_id: id).first
        order.status_id = status_id
        order.save
      end
    end

    render nothing: true
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.where(order_id: params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      puts '-'*80
      puts params
      puts '='*80
      params.require(:order).permit(:status_id, :shipping_price, :order_id, :special_instructions, :total, :delivery_type, :cost)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper

	def caret(current)
		if @sort_by == current
			if @sort_order == 'ASC'
				return '<i class="fa fa-caret-down"></i>'
			else
				return '<i class="fa fa-caret-up"></i>'
			end
		end
		return ''
	end

	# def figure_increase_cost(this_category,this_price)
	# 	cat_id = Category.where(name: this_category).first.id
	# 	if base_item = Item.where(category_id: cat_id, base_item: true).first
	# 		base_fee = base_item.markup.gsub('$','').to_i
	# 	end
	# 	this_price = this_price.gsub('$','').to_i
	# 	if base_fee && this_price
	# 		new_price = this_price - base_fee
	# 		return "$#{this_price}"
	# 	end
	# 	return "$#{this_price}"
	# end

	def quantity_selector(item)
		quantity = @order.order_items.where(item_id: item.id).first.quantity if @order.order_items.where(item_id: item.id).first
		builder = "<select class='dropdown-price-changer price-changer' name='order[items][#{item.category.name}][#{item.id}][quantity]'>"

		builder += "<option value='1' #{quantity==1?'selected':''}>1</option>"
		if item.category.name.downcase == "controllers"		
			if item.base_item
				builder += "<option value='2' #{quantity==2?'selected':''}>2 +#{item.markup}</option>"
			else
				builder += "<option value='2' #{quantity==2?'selected':''}>2</option>"
			end

		end
		
		return builder + "</select>"

	end

	def any_errors(name)
		return 'field_with_errors' if @order.errors.keys.include?(name.to_sym)
		return ''
	end

	def format_init_price
		if @order.total
			return "$#{'%.0f' % @order.total.to_f}"
		end
		return "$#{'%.0f' % $base_fee}"
	end

end

app/views/orders/_form.html.haml
- params["order"] = {} unless params["order"]
- order = Hash.new
- if @order.errors.any?
  #error_explanation.field.form-group
    %h2
      = pluralize(@order.errors.count, "error")
      prohibited this order from being saved:
    %ul
      - @order.errors.full_messages.each do |msg|
        %li= msg
= form_for(@order) do |f|
  -@categories.keys.each do |key|
    - if @categories[key].count > 0
      .p  
        %h3
          =key
      %table.table
        %thead
          %tr
            %th
              = link_to 'Clear', '#', class: 'small clear-radios', data: { table: "#{key.downcase}" } unless Category.has_base?(key)
            %th Name
            %th Image
            %th Price
            %th Quantity
        %tbody
          -@categories[key].each do |item|
            %tr{class: "#{key.downcase} item-row", data: { base: "#{item.base_item}" }}
              %td.clear-radios.center
                = check_box_tag key.downcase, item.id, item.base_item, {class: "radio-order-update", selected: item.base_item , name: "order[items][#{item.category.name}][#{item.id}][ordered]", value: 'true'}
              %td.title= item.title
              %td
                - if item.image_url.present?
                  %img{:alt => "#{item.title}", :src => "#{item.image_url}", :style => "width:50px;height:50px"}
              %td{class: 'price'}
                =humanized_money_with_symbol(item.figure_price)
              %td
                =quantity_selector(item).html_safe
  #total-box
    %h3.text-center
      Total
      %span.total
  - if @order.errors.any?
    #error_explanation.field.form-group
      %h2
        = pluralize(@order.errors.count, "error")
        prohibited this order from being saved:
      %ul
        - @order.errors.full_messages.each do |msg|
          %li= msg
  - unless params["action"] == "edit"
    = recaptcha_tags
  .actions
    - buttn_txt = params["action"] == 'edit' ? 'Update Order' : 'Delivery Information'
    = f.submit buttn_txt, class: 'btn btn-primary'

app/views/orders/_index_table.html.haml
=hidden_field_tag :sort_order, @sort_order, { id: 'sort_order' }
=hidden_field_tag :sort_by, @sort_by, { id: 'sort_by' }
%table.table#order-index.table-condensed
  %thead
    %tr
      %th 
        =caret('order_id').html_safe
        %a{href: '#', class: 'change_sort', data: 'order_id'}
          Order ID
      %th 
        =caret('name').html_safe
        %a{href: '#', class: 'change_sort', data: 'name'}
          Name
      %th 
        =caret('email').html_safe
        %a{href: '#', class: 'change_sort', data: 'email'}
          Email
      %th 
        =caret('total').html_safe
        %a{href: '#', class: 'change_sort', data: 'total'}
          Total Price
      %th 
        =caret('status_id').html_safe
        %a{href: '#', class: 'change_sort', data: 'status_id'}
          Status
      %th
      %th
  %tbody
    - @orders.each do |order|
      %tr{class: 'order-row'}
        %td{class: 'order_id'}= order.order_id
        %td=order.user.name
        %td=order.user.email
        %td=humanized_money_with_symbol(order.total)
        %td= select_tag order.id, options_for_select(@statuses, order.status.id), {class: 'order-change status_id'}
        %td= link_to 'Details', '#', {class: 'btn btn-primary btn-xs order-details', data: "#{order.order_id}"}
        %td= link_to 'Destroy', "orders/#{order.order_id}", method: :delete,class: 'btn btn-danger btn-xs', data: { confirm: 'Are you sure?' }

      %tr{id: "#{order.order_id}", style: "display:none", class: 'details-row'}
        %td{colspan: "4"}

        

app/views/orders/_payment_button.html.haml
%form{:action => "https://www.#{url}.com/cgi-bin/webscr", :method => "post", :target => "_top"}
  %input{:name => "business", :type => "hidden", :value => business}
  %input{:name => "cmd", :type => "hidden", :value => "_xclick"}
  %input{:name => "item_name", :type => "hidden", :value => "BakeMyPIe"}
  %input{:name => "item_number", :type => "hidden", :value => "#{@order.order_id}"}
  %input{:name => "amount", :type => "hidden", :value => "#{@order.total}"}
  %input{:name => "notify_url", :type => "hidden", :value => "#{server_address}/orders/update_status"}
  %input{:name => "currency_code", :type => "hidden", :value => "USD"}
  %input{:name => "button_subtype", :type => "hidden", :value => "services"}
  %input{:name => "no_note", :type => "hidden", :value => "0"}
  %input{:name => "cn", :type => "hidden", :value => "Special instructions?:"}
  %input{:name => "rm", :type => "hidden", :value => "2"}
  %input{:name => "shipping", :type => "hidden", :value => "#{@order.shipping_price}"}
  %input{:name => "no_shipping", :type => "hidden", :value => "2"}
  %input{:name => "return", :type => "hidden", :value => "#{server_address}/orders/appreciation"}
  %input{:name => "cancel_return", :type => "hidden", :value => "#{server_address}/orders/sorry"}
  %input{:name => "bn", :type => "hidden", :value => "PP-BuyNowBF:btn_buynowCC_LG.gif:NonHosted"}
  %input{:alt => "PayPal - The safer, easier way to pay online!", :border => "0", :name => "submit", :src => "https://www.paypalobjects.com/en_US/i/btn/x-click-but6.gif", :type => "image"}

app/views/orders/_verify.html.haml
%p
  Order date: 
  =local_time(order.created_at)
%table.table{:style => "width:100%"}
  %tr
    %th Category
    %th Item Name
    %th Item Price
    %th.item-quantity #
    %th.item-total Total
  - order.order_items.each do |order_item|
    %tr
      %td=order_item.item.category.name
      %td=order_item.item.title
      %td=humanized_money_with_symbol(order_item.price)
      %td.item-quantity=order_item.quantity
      %td=humanized_money_with_symbol(order_item.quantity * order_item.price)
  %tr
    %td{colspan: '3'}
    %td.item-quantity
    %td.item-total
  %tr
    %td{colspan: '3'}
    %td.item-quantity
      %strong
        Total:
    %td.item-total
      %strong
        $
        = order.total 
  - if order.delivery_type == 'delivery'
    %tr
      %td{colspan: '3'}
      %td.item-quantity
        %strong
          Shipping:
      %td.item-total
        %strong
          $
          = order.shipping_price
  %tr
    %td{colspan: '3'}
    %td.item-quantity
      %strong
        Final Total:
    %td.item-total
      %strong
        $
        ='%.2f' % (order.total + order.shipping_price).to_f
- unless @receipt.present? && @receipt
  =link_to 'Edit Order Information', edit_order_path(@order.order_id, user_id: params["user_id"], payment_id: params['payment_id']), class: 'btn btn-default btn-sm'

app/views/orders/appreciation.html.haml
%div.row
  %div.col-md-6.col-md-offset-3.wrapper
    %h2
      Thanks For placing your order
    %p
      I should have this item shipped in 1 - 2 weeks.
    %p
      You should also get a receipt in your email. You can use your email to generate a new email to check for status changes whenever you want.

app/views/orders/edit.html.haml
- @title = 'Edit Order'
%div.row
  %div.col-md-6.col-md-offset-3.wrapper
    = render 'form'
  .col-md-3.text-center
    %h3#total-box-floater
      Total:
      %span.total
        =format_init_price

app/views/orders/index.html.haml
-@title = 'All Orders'
%div.row
  %div.col-md-12.wrapper
    %p{class: 'save_order_button inline-block'}
      %a{href: "#{orders_path}", class: 'btn btn-default'}
        Status
    %p{class: 'pull-right save_order_button inline-block'}
      %a{href: '#', class: 'btn btn-danger hidden', id: 'save_order_edits'}
        Save
    #order_table
      =render partial: 'index_table'
  %div.col-md-1

app/views/orders/new.html.haml
%div.row
  %div.col-md-6.col-md-offset-3.wrapper
    %p.text-center
      All new orders start out with the base model and you can upgrade from there. My fee to set up the Pi is $#{$base_fee.to_s}. I have selected what I consier the base model and everyone must buy this. You can upgrade parts if you want to spend extra. These prices not include shipping which is $#{$shipping}. You may pick up locally if are near enough to me.
    %h4
      Please note. I will get the best items I can for the money. This means that the items in the pictures are used as representations.
    = render 'form'
  .col-md-3.text-center
    #total-box-floater
      %h3
        Total:
        %span.total

app/views/orders/show.html.haml
%div.row
  %div.col-md-8.col-md-offset-2
    %p#notice= notice
    =build_receipt_table(@order.order_items).html_safe
    %p
      %strong Status:
      = @order.status.name
    %p
      %strong Name:
      = @order.name
    %p
      %strong Email:
      = @order.email
    %p
      %strong Perferred contact:
      = @order.perferred_contact
    %p
      %strong Shipping info:
      = @order.shipping_info
    %p
      %strong Delivery type:
      = @order.delivery_type
    %p
      %strong Shipping price:
      = @order.shipping_price
    %p
      %strong Order:
      = @order.order_id
    %p
      %strong Special instructions:
      = @order.special_instructions
    #{link_to 'Home', root_path}

app/views/orders/sorry.html.haml
%div.row
  %div.col-md-6.col-md-offset-3
    %h2
      If you change your mind feel free to order!

app/views/orders/status.html.haml
%div.row
  %div.col-md-8.col-md-offset-2.wrapper
    %p
      Put in the email address used to order with and I will email you an updated recipt
    = form_tag(receipt_users_path, method: "post", class: "form") do
      %br
      %div.form-group
        %p
          = label_tag(:user_email_label, "Order Email:")
        = text_field_tag(:user_email, nil, class: "form-control")
      %div.form-group
        %p
          = label_tag(:user_order_id_label, "Order ID:")
          %small
            If left empty I will email you all orders associtated with your email address.
        = text_field_tag(:user_order_id, nil, class: "form-control")
      %div.form-group
        .actions
          = submit_tag("Check order status",class: 'btn btn-default')
    %br
    Order status will be one of the following:
    %ol
      - @statuses.each do |status|
        %li
          %strong
            =status.name
          =status.description

app/views/orders/verify.html.haml
%div.row
  %div.col-md-8.col-md-offset-2.wrapper
    %h1 Verify Order
    %h3.text-center.red
      Your Order is not complete! 
      %br
      I will start making your order once I get payment confirmation.
    %p
      %h2.text-center
        Buyer Information
      = render partial: 'users/verify'
    %p
      %h2.text-center
        Order
      = render partial: 'orders/verify', locals: {order: @order}
    %p
      %br
      %h4
        Please note. I will get the best items I can for the money. This means that the items in the pictures are used as representations. I will get you the best item I can.
    %p.text-center
      .row
        .col-md-6
          %form{:action => "#{charge_order_path}", :method => "POST"}
            = tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token)            
            %script.stripe-button{"data-amount" => "#{@order.total_cents + @order.shipping_price_cents}", "data-description" => "An Emulation System", "data-image" => "#{image_url('mario_jump.png')}", "data-key" => "#{Rails.configuration.stripe[:publishable_key]}", "data-name" => "Bake My PIe", :src => "https://checkout.stripe.com/checkout.js", "data-email" => "#{@user.email}", "data-panel-label" => "Pay", "data-allow-remember-me" => "false", "data-zip-code" => "true"}
        .col-md-6
          %form#myform{:action => "#{cash_order_path}", :method => "POST"}
            = tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) 
            %input{:name => "name", :type => "hidden", :value => "cash"}
            %input{:name => "user_id", :type => "hidden", :value => "#{@user.id}"}
            %a.mimic-strip-button{:onclick => "document.getElementById('myform').submit();"}
              %span.mimic-strip-button-span
                Pay Cash