config/routes.rb
RetroPie::Application.routes.draw do

  resources :faqs

  resources :payments

  resources :order_items

  resources :statuses
  
  resources :users do
    collection do
      post 'receipt'
    end
  end

  resources :items

  resources :orders do
    member do
      patch 'update'
      get 'verify'
      post 'charge'
      post 'cash'
    end
    collection do
      post 'update_status'
      get 'appreciation'
      get 'sorry'
      get 'status'
      get 'stats'
    end
  end

  resources :categories

  get 'manage', to: 'static_pages#manage'

  post 'scrape_data', to: 'items#scrape_data'

  get 'contact_me', to: 'static_pages#contact_me'
  post 'contact_me', to: 'static_pages#contact_me'

  root 'static_pages#index'

end

app/models/payment.rb
class Payment < ActiveRecord::Base
	belongs_to :order

	monetize :amount_cents

	# after_initialize :set_defaults

	# def set_defaults
	# 	self.status = 'processing'
	# 	self.save
	# end

	# def amount
	# 	if self.status == 'pending' || self.status == nil
	# 		self.order.total
	# 	else
	# 		return super
	# 	end
	# end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, except: [:update_status, :appreciation]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
    @user = User.find_by_id(params['user_id'])
    @order = Order.find_by_order_id(params['order_id'])
  end

  # GET /payments/1/edit
  def edit
    @order = Order.find_by_order_id(params["order_id"])
    @user = User.find_by_id(params["user_id"])
    @payment = Payment.find_by_id(params["id"])
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)
    respond_to do |format|
      if @payment.save
        session[:_bmp_payment_id] = @payment.id
        format.html { redirect_to verify_order_path(params["payment"]["order_order_id"], user_id: params["payment"]["user_id"], payment_id: @payment.id), notice: 'Payment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @payment }
      else
        format.html { render action: 'new' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    @order = Order.find_by_order_id(params["payment"]["order_id"])

    @order = Order.find_by_order_id(params["payment"]["order_order_id"]) unless @order
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to verify_order_path(@order.order_id, user_id: params["user_id"], payment_id: @payment.id ) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:order_id, :amount, :type, :status, :meta)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.haml
= form_for(@payment, html: {class: 'form-horizontal'}) do |f|
  - if @payment.errors.any?
    #error_explanation
      %h2
        = pluralize(@payment.errors.count, "error")
        prohibited this payment from being saved:
      %ul
        - @payment.errors.full_messages.each do |msg|
          %li= msg
  .form-group.form-group-sm
    = f.label :amount, 'Amount Owed'
    :escaped
      -
    = f.label :amount, "$#{'%.0f' % @order.total}"
    %br
    = f.label :amount, 'Order ID'
    = f.label :order_id, "$#{@order.order_id}", name: "payment[order_id]"
    
    = f.hidden_field :user_id, value: @user.id, name: "payment[user_id]"
    = f.hidden_field :order_id, value: @order.id, name: "payment[order_id]"
    = f.hidden_field :order_order_id, value: @order.order_id, name: "payment[order_order_id]"
    = f.hidden_field :amount, value: @order.total, name: "payment[amount]"
  .form-group.form-group-sm
    = f.submit 'Verify Information', class: 'btn btn-primary'

app/views/payments/_verify.html.haml
%p
  %strong Amount:
  $
  = payment.amount
- unless @receipt.present? && @receipt
  =link_to 'Edit Payment Information', edit_payment_path(param("payment_id"), order_id: param('order_id'), user_id: param('user_id')), class: 'btn btn-default btn-sm'

app/views/payments/edit.html.haml
%div.row
  %div.col-md-6.col-md-offset-2
    %h2
      Edit Payment
    = render 'form'

app/views/payments/index.html.haml
%h1 Listing payments
%table
  %thead
    %tr
      %th Order
      %th Amount
      %th
      %th
      %th
  %tbody
    - @payments.each do |payment|
      %tr
        %td= payment.order_id
        %td= payment.amount
        %td= link_to 'Show', payment
        %td= link_to 'Edit', edit_payment_path(payment)
        %td= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' }
%br
  = link_to 'New Payment', new_payment_path

app/views/payments/new.html.haml
-@title = "Payment Information"
%div.row
  %div.col-md-6.col-md-offset-3
    %h2
      Payment
    = render partial: 'form'
    = link_to 'Back', edit_user_path(param('user_id'), order_id: param('order_id'), payment_id: param('payment_id')), class: 'btn btn-default btn-xs'

app/views/payments/show.html.haml
%p#notice= notice
%p
  %strong Order:
  = @payment.order_id
%p
  %strong Amount:
  = @payment.amount
= link_to 'Edit', edit_payment_path(@payment)
|
#{link_to 'Back', payments_path}